# Generated by Django 5.2.6 on 2025-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
