# Generated by Django 5.2.6 on 2025-11-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_city_event_events_even_city_533bd7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.TextField(blank=True, default='', help_text='URL or base64 data URL for event image'),
        ),
    ]
