# Generated by Django 5.2.6 on 2025-11-28 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistration_eventreminder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Field label shown to user (e.g., 'Full Name', 'Email Address')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email'), ('phone', 'Phone Number'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons')], default='text', help_text='Type of input field', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Is this field mandatory?')),
                ('placeholder', models.CharField(blank=True, help_text="Placeholder text (e.g., 'Enter your email')", max_length=200)),
                ('help_text', models.CharField(blank=True, help_text='Additional help text below field', max_length=500)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for dropdown/radio/checkbox (list of strings)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('pattern', models.CharField(blank=True, help_text='Regex pattern for validation', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Event Registration', help_text='Form title shown to users', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions or welcome message for form')),
                ('confirmation_message', models.TextField(default='Thank you for registering! You will receive a confirmation email shortly.', help_text='Message shown after successful registration')),
                ('allow_guest_registration', models.BooleanField(default=True, help_text='Allow users to register without logging in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, help_text="User's responses to custom registration fields"),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['contact_email'], name='events_even_contact_cf86cb_idx'),
        ),
        migrations.AddField(
            model_name='eventregistrationform',
            name='event',
            field=models.OneToOneField(help_text='Event this form belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='registration_form', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventregistrationfield',
            name='form',
            field=models.ForeignKey(help_text='Form this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='events.eventregistrationform'),
        ),
        migrations.AddIndex(
            model_name='eventregistrationfield',
            index=models.Index(fields=['form', 'order'], name='events_even_form_id_dc1dba_idx'),
        ),
    ]
