# Generated by Django 5.2.6 on 2025-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_custom_registration_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='contact_email',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
