# Generated by Django 5.2.6 on 2025-12-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_change_contact_email_to_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approval_message',
            field=models.TextField(blank=True, default='Your registration is pending approval. You will receive an email once reviewed.', help_text='Message shown to users when their registration is pending approval'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_form_config',
            field=models.JSONField(blank=True, default=list, help_text='Custom registration form fields configuration. List of field definitions.'),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='If true, registrations need admin approval before being confirmed'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes from admin during review'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the registration was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('waitlist', 'Waitlist')], default='confirmed', max_length=20),
        ),
    ]
