# Generated by Django 5.2.6 on 2025-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Hotel', 'Hotel'), ('Apartment', 'Apartment'), ('Guest House', 'Guest House'), ('Homestay', 'Homestay')], max_length=20)),
                ('district', models.CharField(db_index=True, max_length=120)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('priceNight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('distanceKm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['district', 'name'],
                'indexes': [models.Index(fields=['district', 'type'], name='stays_stay_distric_b0d922_idx')],
            },
        ),
    ]
