# Generated by Django 5.2.6 on 2025-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_stay_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='agoda_url',
            field=models.URLField(blank=True, help_text='Direct link to this property on Agoda', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='booking_com_url',
            field=models.URLField(blank=True, help_text='Direct link to this property on Booking.com', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='booking_provider',
            field=models.CharField(blank=True, choices=[('booking.com', 'Booking.com'), ('agoda', 'Agoda'), ('both', 'Both Platforms'), ('direct', 'Direct Booking')], default='booking.com', help_text='Primary booking platform for this property', max_length=50),
        ),
    ]
