# Generated by Django 5.2.6 on 2025-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0003_stay_agoda_url_stay_booking_com_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email for tourists to contact the owner directly', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number for direct booking inquiries', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='contact_whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number for instant messaging', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='is_internal',
            field=models.BooleanField(default=True, help_text='True for stays created by owners on our platform, False for external affiliate stays'),
        ),
    ]
