# Generated by Django 5.2.6 on 2025-11-21 15:40

import django.db.models.deletion
import stays.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0004_stay_contact_email_stay_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=stays.models.stay_image_upload_path),
        ),
        migrations.CreateModel(
            name='StayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=stays.models.stay_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_images', to='stays.stay')),
            ],
            options={
                'ordering': ['-is_primary', 'order', '-uploaded_at'],
                'indexes': [models.Index(fields=['stay', 'is_primary'], name='stays_stayi_stay_id_a657c7_idx')],
            },
        ),
    ]
