# Generated by Django 5.2.6 on 2025-12-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0005_stay_main_image_stayimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Whether the accommodation is currently open/operational'),
        ),
    ]
