# Generated by Django 5.2.6 on 2025-12-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0006_stay_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='is_open',
        ),
    ]
