# Generated by Django 5.2.6 on 2026-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0007_remove_is_open_from_stays'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Whether the accommodation is currently open/accepting bookings'),
        ),
    ]
