# Generated by Django 5.2.6 on 2025-10-26 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price_cents', models.IntegerField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X / Twitter'), ('ig', 'Instagram'), ('tt', 'TikTok'), ('fb', 'Facebook')], max_length=8)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('is_tourism_related', models.BooleanField(default=False)),
                ('sentiment', models.SmallIntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.place')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='analytics_s_created_017dca_idx'), models.Index(fields=['place', 'created_at'], name='analytics_s_place_i_68c2e2_idx')],
            },
        ),
    ]
