# Generated by Django 5.2.6 on 2025-10-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='post_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='analytics_p_name_f2e14d_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city', 'state'], name='analytics_p_city_d8244b_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['place', 'created_at'], name='analytics_s_place_i_68c2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['created_at'], name='analytics_s_created_017dca_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialpost',
            constraint=models.UniqueConstraint(fields=('platform', 'post_id'), name='uniq_platform_postid'),
        ),
    ]
