# Generated by Django 5.2.6 on 2025-11-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_place_description_alter_socialpost_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_posts', to='analytics.socialpost')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SentimentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('-date', '-count'),
                'indexes': [models.Index(fields=['topic'], name='analytics_s_topic_45465a_idx'), models.Index(fields=['sentiment'], name='analytics_s_sentime_976dd3_idx'), models.Index(fields=['category'], name='analytics_s_categor_500825_idx'), models.Index(fields=['date'], name='analytics_s_date_56c91e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostClean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.place')),
                ('raw_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_post', to='analytics.postraw')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sentiment'], name='analytics_p_sentime_0dec28_idx'), models.Index(fields=['poi'], name='analytics_p_poi_id_167786_idx')],
            },
        ),
    ]
