# Generated by Django 5.2.6 on 2025-10-27 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_socialpost_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='socialpost',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveIndex(
            model_name='socialpost',
            name='analytics_s_created_017dca_idx',
        ),
        migrations.RemoveIndex(
            model_name='socialpost',
            name='analytics_s_place_i_68c2e2_idx',
        ),
        migrations.RemoveField(
            model_name='place',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='price_cents',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='inserted_at',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='is_tourism_related',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='text',
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='currency',
            field=models.CharField(blank=True, default='MYR', max_length=10),
        ),
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='is_tourism',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analytics.place'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
