# Generated by Django 5.2.6 on 2025-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_place_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
