# Generated by Django 5.2.6 on 2025-11-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_socialpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='URL to place image', max_length=500),
        ),
    ]
