# Generated by Django 5.2.6 on 2025-11-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.TextField(blank=True, default='', help_text='URL or base64 data URL for place image'),
        ),
    ]
