# Generated by Django 5.2.6 on 2025-11-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_change_image_url_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='AI classification confidence (0-100%)'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', help_text='AI-classified sentiment category', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='Numerical sentiment score: -1.0 (very negative) to +1.0 (very positive)'),
        ),
    ]
