# Generated by Django 5.2.6 on 2025-11-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_add_sentiment_fields'),
        ('stays', '0005_stay_main_image_stayimage'),
        ('vendors', '0004_vendor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='stay',
            field=models.ForeignKey(blank=True, help_text='Related accommodation mentioned in post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='stays.stay'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Related restaurant/vendor mentioned in post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Related tourism destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analytics.place'),
        ),
    ]
