# Generated by Django 5.2.6 on 2025-11-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_add_vendor_stay_to_socialpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Full physical address'),
        ),
        migrations.AddField(
            model_name='place',
            name='amenities',
            field=models.JSONField(blank=True, default=dict, help_text='Facilities like parking, WiFi, wheelchair access, etc.'),
        ),
        migrations.AddField(
            model_name='place',
            name='best_time_to_visit',
            field=models.CharField(blank=True, default='', help_text='Best season/time to visit', max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='place',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='google_maps_url',
            field=models.URLField(blank=True, default='', help_text='Google Maps link'),
        ),
        migrations.AddField(
            model_name='place',
            name='official_website',
            field=models.URLField(blank=True, default='', help_text='Official website or tourism board link'),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.TextField(blank=True, default='', help_text="Opening hours (e.g., 'Mon-Fri: 9AM-6PM')"),
        ),
        migrations.AddField(
            model_name='place',
            name='tripadvisor_url',
            field=models.URLField(blank=True, default='', help_text='TripAdvisor page link'),
        ),
        migrations.AddField(
            model_name='place',
            name='wikipedia_url',
            field=models.URLField(blank=True, default='', help_text='Wikipedia article link'),
        ),
    ]
