# Generated by Django 5.2.6 on 2025-12-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_place_address_place_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Whether the place is currently open/operational'),
        ),
    ]
