# Generated by Django 5.2.6 on 2026-01-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_place_is_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the place is active/visible on the platform'),
        ),
        migrations.AddField(
            model_name='place',
            name='is_council_managed',
            field=models.BooleanField(default=True, help_text='True if managed by tourism council (admin), False if privately managed'),
        ),
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Place owner user who manages this attraction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
