# Generated by Django 5.2.6 on 2025-10-24 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('is_in_kedah', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('intra_kedah', 'Intra-Kedah'), ('coming_to_kedah', 'Coming to Kedah'), ('leaving_kedah', 'Leaving Kedah')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('polyline', models.JSONField(blank=True, null=True)),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='transport.place')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='transport.place')),
            ],
            options={
                'indexes': [models.Index(fields=['route_type'], name='transport_r_route_t_38c7fe_idx')],
                'unique_together': {('from_place', 'to_place')},
            },
        ),
    ]
