# Generated by Django 5.2.6 on 2025-10-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('from_place', 'to_place', 'route_type')},
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='transport_p_name_ff971e_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_in_kedah'], name='transport_p_is_in_k_aa414c_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['from_place', 'to_place'], name='transport_r_from_pl_212a07_idx'),
        ),
    ]
