# Generated by Django 5.2.6 on 2025-11-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_route_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('transport_mode', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('days_of_week', models.JSONField(help_text='Array of days when this schedule runs [0-6], 0=Monday')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('seats_available', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transport.route')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='RouteOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seats_total', models.IntegerField()),
                ('seats_taken', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='transport.schedule')),
            ],
            options={
                'verbose_name_plural': 'route occupancies',
                'ordering': ['-date', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='RouteDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('delay_minutes', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('on-time', 'On Time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='on-time', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='transport.schedule')),
            ],
            options={
                'ordering': ['-date', '-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('impact_level', models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact')], max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='transport.route')),
            ],
            options={
                'ordering': ['start_date', '-impact_level'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='transport_m_start_d_5a457b_idx'), models.Index(fields=['impact_level'], name='transport_m_impact__fd680e_idx'), models.Index(fields=['status'], name='transport_m_status_8fb933_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['route', 'transport_mode'], name='transport_s_route_i_a6e3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['provider'], name='transport_s_provide_900efb_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['departure_time'], name='transport_s_departu_cd3bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='routeoccupancy',
            index=models.Index(fields=['date'], name='transport_r_date_fd247c_idx'),
        ),
        migrations.AddIndex(
            model_name='routeoccupancy',
            index=models.Index(fields=['schedule'], name='transport_r_schedul_be0efb_idx'),
        ),
        migrations.AddIndex(
            model_name='routedelay',
            index=models.Index(fields=['date'], name='transport_r_date_da6df6_idx'),
        ),
        migrations.AddIndex(
            model_name='routedelay',
            index=models.Index(fields=['status'], name='transport_r_status_35b643_idx'),
        ),
        migrations.AddIndex(
            model_name='routedelay',
            index=models.Index(fields=['schedule'], name='transport_r_schedul_bad5ad_idx'),
        ),
    ]
