# Generated by Django 5.2.6 on 2025-11-11 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_schedule_routeoccupancy_routedelay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
