# Generated by Django 5.2.6 on 2025-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('cuisines', models.JSONField(blank=True, default=list)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city'], name='vendors_ven_city_4e1b89_idx')],
            },
        ),
    ]
