# Generated by Django 5.2.6 on 2025-11-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_created_at_vendor_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_halal', models.BooleanField(default=True)),
                ('spiciness_level', models.IntegerField(default=0)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='vendors.vendor')),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['vendor', 'category'], name='vendors_men_vendor__c47746_idx'), models.Index(fields=['is_available'], name='vendors_men_is_avai_f4410e_idx'), models.Index(fields=['is_vegetarian'], name='vendors_men_is_vege_62a980_idx'), models.Index(fields=['is_halal'], name='vendors_men_is_hala_18fb82_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='vendors.vendor')),
            ],
            options={
                'ordering': ['day_of_week', 'open_time'],
                'indexes': [models.Index(fields=['vendor', 'day_of_week'], name='vendors_ope_vendor__dc79a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['vendor', 'start_date', 'end_date'], name='vendors_pro_vendor__19b12f_idx'), models.Index(fields=['is_active'], name='vendors_pro_is_acti_f86a50_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('party_size', models.IntegerField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vendors.vendor')),
            ],
            options={
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['vendor', 'date'], name='vendors_res_vendor__3b5c4b_idx'), models.Index(fields=['status'], name='vendors_res_status_2285b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('verified_visit', models.BooleanField(default=False)),
                ('food_rating', models.IntegerField(blank=True, null=True)),
                ('service_rating', models.IntegerField(blank=True, null=True)),
                ('ambience_rating', models.IntegerField(blank=True, null=True)),
                ('value_rating', models.IntegerField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['vendor', 'date'], name='vendors_rev_vendor__a27e2c_idx'), models.Index(fields=['rating'], name='vendors_rev_rating_9609b2_idx'), models.Index(fields=['verified_visit'], name='vendors_rev_verifie_e129ce_idx')],
            },
        ),
    ]
