# Generated by Django 5.2.6 on 2025-11-11 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_menuitem_openinghours_promotion_reservation_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Vendor user who owns this vendor profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_vendors', to=settings.AUTH_USER_MODEL),
        ),
    ]
