# Generated by Django 5.2.6 on 2025-11-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, help_text='Full street address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='amenities',
            field=models.JSONField(blank=True, default=dict, help_text='Facilities like parking, wifi, wheelchair_accessible, etc.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Banner/cover image URL'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, help_text='About the restaurant'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='dress_code',
            field=models.CharField(blank=True, help_text='e.g., Casual, Smart Casual, Formal', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='established_year',
            field=models.IntegerField(blank=True, help_text='Year the restaurant opened', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs for gallery'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Restaurant logo image URL'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='official_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='price_range',
            field=models.CharField(blank=True, choices=[('$', 'Budget (< RM30)'), ('$$', 'Moderate (RM30-80)'), ('$$$', 'Upscale (RM80-150)'), ('$$$$', 'Fine Dining (> RM150)')], default='$$', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reservation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='takeaway_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tripadvisor_url',
            field=models.URLField(blank=True),
        ),
    ]
