# Generated by Django 5.2.6 on 2025-12-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_address_vendor_amenities_vendor_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Whether the restaurant is currently open/operational'),
        ),
    ]
