# Generated by Django 5.2.8 on 2026-01-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_halal',
            field=models.BooleanField(default=True, help_text='Whether the restaurant is Halal certified'),
        ),
    ]
