# Generated by Django 5.2.6 on 2026-01-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_verification_notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes about business ownership verification'),
        ),
        migrations.AddField(
            model_name='user',
            name='claimed_stay_id',
            field=models.IntegerField(blank=True, help_text='ID of the hotel/stay this user claims to own (pending approval)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='claimed_vendor_id',
            field=models.IntegerField(blank=True, help_text='ID of the restaurant/vendor this user claims to own (pending approval)', null=True),
        ),
    ]
