# Generated by Django 5.2.6 on 2026-01-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_business_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text="Admin's private notes about this user/business"),
        ),
        migrations.AddField(
            model_name='user',
            name='business_registration_number',
            field=models.CharField(blank=True, default='', help_text='Official business registration/license number (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Contact phone number for verification', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Upload business verification documents (ID, business license, etc.)', null=True, upload_to='verification_documents/'),
        ),
    ]
