# Generated by Django 5.2.6 on 2026-01-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_admin_notes_user_business_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='claimed_place_id',
            field=models.IntegerField(blank=True, help_text='ID of the place/attraction this user claims to own (pending approval)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('stay_owner', 'Stay Owner'), ('place_owner', 'Place Owner')], default='vendor', help_text='User role determines access permissions', max_length=20),
        ),
    ]
